version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install time
      - export BUCKET=petark-sam-cicd-test-deployment
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml